import { TRANSLIT_CODEPOINTS_CYRILLIC_LETTERS, TRANSLIT_CODEPOINTS_LATIN_LETTERS } from './builtin-codepoints';
import { invertRules, type TranslitRules } from './rule';

// non-standard rules which can be used with a US keyboard. uses the "common
// transliteration" column from:
// https://en.wikipedia.org/wiki/Russian_alphabet
export const TRANSLIT_RULES_NONSTANDARD_LATIN_RUCYRILLIC: TranslitRules = {
    map: [
        { in: 'a', out: 'а' },
        { in: 'b', out: 'б' },
        { in: 'v', out: 'в' },
        { in: 'g', out: 'г' },
        { in: 'd', out: 'д' },
        { in: 'ye', out: 'е' },
        { in: 'je', out: 'е' },
        { in: 'e', out: 'е' },
        { in: 'yo', out: 'ё' },
        { in: 'jo', out: 'ё' },
        { in: 'ë', out: 'ё' },
        { in: 'zh', out: 'ж' },
        { in: 'ž', out: 'ж' },
        { in: 'z', out: 'з' },
        { in: 'i', out: 'и' },
        { in: 'y', out: 'й' },
        { in: 'i', out: 'й' },
        { in: 'j', out: 'й' },
        { in: 'k', out: 'к' },
        { in: 'l', out: 'л' },
        { in: 'm', out: 'м' },
        { in: 'n', out: 'н' },
        { in: 'o', out: 'о' },
        { in: 'p', out: 'п' },
        { in: 'r', out: 'р' },
        { in: 's', out: 'с' },
        { in: 't', out: 'т' },
        { in: 'u', out: 'у' },
        { in: 'f', out: 'ф' },
        { in: 'kh', out: 'х' },
        { in: 'h', out: 'х' },
        { in: 'ts', out: 'ц' },
        { in: 'c', out: 'ц' },
        { in: 'ch', out: 'ч' },
        { in: 'č', out: 'ч' },
        { in: 'sh', out: 'ш' },
        { in: 'š', out: 'ш' },
        { in: 'shch', out: 'щ' }, // FIXME: shch will create conflicts
        { in: 'sch', out: 'щ' },
        { in: 'šč', out: 'щ' },
        { in: 'śś', out: 'щ' },
        { in: '"', out: 'ъ' },
        { in: 'y', out: 'ы' },
        { in: "'", out: 'ь' },
        { in: 'e', out: 'э' },
        { in: 'è', out: 'э' },
        { in: 'yu', out: 'ю' },
        { in: 'ju', out: 'ю' },
        { in: 'ya', out: 'я' },
        { in: 'ja', out: 'я' },
    ],
    inCodePointRanges: TRANSLIT_CODEPOINTS_LATIN_LETTERS,
    outCodePointRanges: TRANSLIT_CODEPOINTS_CYRILLIC_LETTERS,
};

export const TRANSLIT_RULES_NONSTANDARD_RUCYRILLIC_LATIN = invertRules(TRANSLIT_RULES_NONSTANDARD_LATIN_RUCYRILLIC);

export const TRANSLIT_RULES_CYRILLISCH: TranslitRules = {
    map: [
        { in: 'а', out: 'a' },
        { in: 'б', out: 'b' },
        { in: 'ч', out: 'ch' },
        { in: 'д', out: 'd' },
        { in: 'е', out: 'e' },
        { in: 'ф', out: 'f' },
        { in: 'г', out: 'g' },
        { in: 'х', out: 'h' },
        { in: 'и', out: 'i' },
        { in: 'џ', out: 'j' },
        { in: 'к', out: 'k' },
        { in: 'л', out: 'l' },
        { in: 'м', out: 'm' },
        { in: 'н', out: 'n' },
        { in: 'о', out: 'o' },
        { in: 'п', out: 'p' },
        { in: 'р', out: 'r' },
        { in: 'с', out: 's' },
        { in: 'ш', out: 'sch' },
        { in: 'т', out: 't' },
        { in: 'у', out: 'u' },
        { in: 'в', out: 'v' },
        { in: 'ў', out: 'w' },
        { in: 'қ', out: 'x' },
        { in: 'ј', out: 'y' },
        { in: 'з', out: 'z' },
        { in: 'э', out: 'ä' },
        { in: 'ң', out: 'ng' },
        { in: 'ц', out: 'ts' },
        { in: 'ж', out: 'zh' },
        { in: 'ћ', out: 'th' },
        { in: 'ђ', out: 'dh' },
    ],
    inCodePointRanges: TRANSLIT_CODEPOINTS_LATIN_LETTERS,
    outCodePointRanges: TRANSLIT_CODEPOINTS_CYRILLIC_LETTERS,
};
